#!/bin/zsh
# Jean-Philippe Goulet

##### COMMANDS

alias reload="source ~/.zshrc"
alias lsd="ls -ld */"
alias ll="ls -l"
alias lf="ls | fzf"
alias malias="$EDITOR $HOME/dotfiles/aliases"
alias open="xdg-open"

##### NAVIGATION SHORTCUTS

alias dbdir="cd /mnt/data/Dropbox"
alias docs="cd $HOME/Documents"

alias pj="cd $HOME/Projects"
alias pjl="cd $HOME/Projects ; ls -l"

alias sb="cd $HOME/Sandbox"
alias sbl="cd $HOME/Sandbox ; ls -l"

alias gdr="cd '$HOME/Google Drive/'"
alias uni="gdr ; cd Université"

##### APPLICATIONS SHORTCUTS

alias archey="archey3"
alias mpad="mousepad"
# Note : The `env` is not required for most shell, but it is for `fish` and does
# not break the others
alias tmux="env TERM=xterm-256color /usr/bin/tmux -2"

##### MISC

# Remove the libs coming with steam, so that steam uses the updated libs instead
# Source: https://bbs.archlinux.org/viewtopic.php?id=211822#p1624603
alias rmbadsteamlibs='find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete'
alias rmbadsteamlibslocal='find ~/.local/share/Steam/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete'

##### GIT

alias gl="git log"
alias gl1="git log --pretty=oneline"
alias gs="git status"
