#!/bin/bash
# Change directory and list it
cdl() {
    cd $1
    ls
}

# Change directory and lists it with hidden files
cdla() {
    cd $1
    ls -la
}

tarinc() {
    ssh $1@tarin.dinf.usherbrooke.ca
}

fixntfs() {
    sudo ntfsfix $1
    sudo ntfs-3g $1 $2
}

refreshx() {
    xrefresh
}

# Find a file using locate and FuZzyFind and start it with xdg-open
fzf-start() { xdg-open "$(fzf-locate)" ;}
fzf-locate() { locate "*" | fzf -e;}

vim-open() { vim "$(fzf-locate)"}

# Usage : mksymlink `SOURCE` `TARGET` `[MODE]`
#
# Desc : Move the file to another directory and create a symlink to replace it
#   The `SOURCE` is the initial file (which will be a symlink afterwards)
#   The `TARGET` is the final location of the file
#   The `MODE` if 'hard|h|--hard', it will make a hardlink, otherwise it will make a symlink
#
# Example : `mksymlink ~/.zshrc ~/dotfiles/zshrc`
#   It will copy the ~/.zshrc into the dotfiles folder and create a symlink to it
mksymlink(){
    mv $1 $2

    if  [ "$3" = "h" ] || [ "$3" = "-h" ]|| [ "$3" = "hard" ] || [ "$3" = "--hard" ]; then
        ln -v $2 $1
    else
        ln -sv $2 $1
    fi
}

# Usage : revertsymlink `SOURCE` `TARGET`
#
# Desc : Move back the original file instead of the link (the inverse of `mksymlink`)
#   The `SOURCE` is the link location (which will be the actual file afterwards)
#   The `TARGET` is the file location
#
# Example : `reversymlink ~/.zshrc ~/dotfiles/zshrc`
#   It will replace the ~/.zshrc link with the file at ~/dotfiles/zshrc
revertsymlink(){
    mv -v $2 $1
}
