#!/bin/bash
# Change directory and list it
cdl()
{
    cd $1
    ls
}


# Change directory and lists it with hidden files
cdla()
{
    cd $1
    ls -la
}

tarinc()
{
    ssh $1@tarin.dinf.usherbrooke.ca
}

fixntfs()
{
    sudo ntfsfix $1
    sudo ntfs-3g $1 $2
}

refreshx()
{
    xrefresh
}

# Find a file using locate and FuZzyFind and start it with xdg-open
fzf-start() { xdg-open "$(fzf-locate)" ;}
fzf-locate() { locate "*" | fzf -e;}

vim-open() { vim "$(fzf-locate)"}
